import { Inter, Roboto } from 'next/font/google'

import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ weight:['400','500', '700', '900'] ,subsets: ['latin'] })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    default:'Next Hero',
    template:'%s | Next Hero'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Navbar/>
        
        {children}
        <footer className="bg-blue-600">
          <h1>This is Footer</h1>
        </footer>
      </body>
    </html>
  );
}
