import { getPost } from '@/services/postApi';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import React from 'react';

export const metadata = {
  title: 'Posts',
  description: "Generated by create next app",
  keywords: ['Posts', 'Posts Page']
};

const page = async () => {
  const postData = await getPost();

  // If there's post data, redirect to the first post
  // if (postData && postData.length > 0) {
  //   redirect(`/posts/${postData[0].id}`);
  // }

  return (
    <div className='min-h-screen'>
      <h1>All Posts</h1>
      <div className='grid grid-cols-4 gap-6'>
        {postData.map((post) => (
          <div key={post.id} className='border-2 p-6'>
            <h1 className='font-bold text-xl'>{post.title}</h1>
            <h1>{post.body}</h1>
            <button className='p-2 bg-red-600 text-white'>
              <Link href={`/posts/${post.id}`}>View Details</Link>
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};

export default page;
